sudo: true

language: node_js

node_js:
  - "node"
  - "7"
  - "6"

cache:
  directories:
    - node_modules

notifications:
  email: false

services:
  - docker

#env:
#  - HUBOT_TREE01='https://github.com/genebean/tree-planter.git,http://127.0.0.1:8081,tree-planter-via-http'
#  - HUBOT_TREE02='git@github.com:genebean/tree-planter.git,http://127.0.0.1:8081,tree-planter-via-ssh'

before_install:
  - mkdir ${TRAVIS_BUILD_DIR}/trees
  - docker pull genebean/tree-planter:latest
  - docker run -d -p 127.0.0.1:8081:8080 --name planted_travis -v ${TRAVIS_BUILD_DIR}/trees:/opt/trees -e LOCAL_USER_ID=`id -u $USER` genebean/tree-planter
  - docker ps -a
